Add 'install' make target
Dushistov/qt_monkey pull request #10
Opened 2018-05-22 20:56 UTC by drons

2018-05-22 21:18 UTC, Dushistov requested changes
Thank you for contribution, there are some issues that I would like to resolve before merging PR.

2018-05-22 21:18 UTC, Dushistov commented on CMakeLists.txt
> +install(FILES ${qt_monkey_SOURCE_DIR}/contrib/json11/json11.hpp DESTINATION include/json11)
This is private header, json11 library internally used for cooperation between qtmonkey application and agent,
so no sense to export it.

2018-05-22 21:18 UTC, Dushistov commented on CMakeLists.txt
> +install(FILES ${qt_monkey_BINARY_DIR}/libcommon_app_lib.a
libcommon_app_lib.a is used to share code between qtmonkey_app and qtmonkey_gui,
so there is no sense to export/install it.

2018-05-23 01:20 UTC, merged

2018-05-23 19:46 UTC, drons commented
Thanks!